import type { Metadata } from "next";

import BootstrapJS from "./bootstrap";
import "./stylesheets/globals.css";

export const metadata: Metadata = {
  title: "Algorithm Visualizer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <BootstrapJS />
        <header>
          <nav className="navbar">
            <div className="container">
              <span className="navbar-brand heading mb-0 h1">
                Algorithm Visualizer
              </span>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
