import type { Metadata } from "next";
import "./globals.css";

import BootstrapJS from "./bootstrap";
import CodeIcon from "@mui/icons-material/Code";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemText from "@mui/material/ListItemText";
import ListSubheader from "@mui/material/ListSubheader";
import Slider from "@mui/material/Slider";
import Stack from "@mui/material/Stack";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import PlayArrowIcon from '@mui/icons-material/PlayArrow';
import PauseIcon from '@mui/icons-material/Pause';
import StairsIcon from '@mui/icons-material/Stairs';
import RestartAltIcon from '@mui/icons-material/RestartAlt';

export const metadata: Metadata = {
  title: "Algorithm Visualizer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <BootstrapJS />
        <header>
          <nav className="navbar">
            <div className="container">
              <span className="navbar-brand heading mb-0 h1">
                Algorithm Visualizer
              </span>
            </div>
          </nav>
        </header>
        <aside>
          <List
            className="algoList"
            sx={{
              maxWidth: 250,
              position: "fixed",
              left: 0,
              minHeight: "100vh",
              overflow: "auto",
              "& ul": { padding: 0 },
            }}
            subheader={<CodeIcon />}
          >
            {["Sorting"].map((sectionId) => (
              <li key={`section-${sectionId}`}>
                <ListSubheader className="algoType">{sectionId}</ListSubheader>
                <ul>
                  {["Bubble Sort", "Merge Sort", "Quick Sort"].map((item) => (
                    <ListItem key={`item-${sectionId}-${item}`}>
                      <ListItemText primary={item} />
                    </ListItem>
                  ))}
                </ul>
              </li>
            ))}
          </List>
        </aside>
        {children}
        <aside style={{ position: "fixed", right: 0 }}>
          <div
            className="cotrols"
            style={{
              maxWidth: 350,
              minHeight: "100vh",
              overflow: "auto",
            }}
          >
            <div className="general">
              speed:
              <br />
              <Slider
                defaultValue={50}
                aria-label="Default"
                valueLabelDisplay="auto"
                style={{
                  padding: '1em 10px',
                  width: '9em'
                }}
              />
              <br />
              <Button variant="outlined">Generate New Input</Button>
              <Stack spacing={2} direction="row">
                <IconButton aria-label="pause">
                  <PauseIcon />
                  <PlayArrowIcon />
                </IconButton>
                <IconButton aria-label="pause">
                  <StairsIcon />
                </IconButton>
                <IconButton aria-label="pause">
                  <RestartAltIcon />
                </IconButton>
              </Stack>
            </div>
          </div>
        </aside>
      </body>
    </html>
  );
}
