import type { Metadata } from "next";
import "./globals.css";

import BootstrapJS from "./bootstrap";
import CodeIcon from "@mui/icons-material/Code";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemText from "@mui/material/ListItemText";
import ListSubheader from "@mui/material/ListSubheader";
import Slider from "@mui/material/Slider";
import Stack from "@mui/material/Stack";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import PlayArrowIcon from "@mui/icons-material/PlayArrow";
import PauseIcon from "@mui/icons-material/Pause";
import StairsIcon from "@mui/icons-material/Stairs";
import RestartAltIcon from "@mui/icons-material/RestartAlt";

export const metadata: Metadata = {
  title: "Algorithm Visualizer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <BootstrapJS />
        <header>
          <nav className="navbar">
            <div className="container">
              <span className="navbar-brand heading mb-0 h1">
                Algorithm Visualizer
              </span>
            </div>
          </nav>
        </header>
        <aside>
          <List
            className="algoList"
            sx={{
              "& ul": { padding: 0 },
            }}
            subheader={<CodeIcon />}
          >
            {["Sorting"].map((sectionId) => (
              <li key={`section-${sectionId}`}>
                <ListSubheader className="algoType">{sectionId}</ListSubheader>
                <ul>
                  {["Bubble Sort", "Merge Sort", "Quick Sort"].map((item) => (
                    <ListItem key={`item-${sectionId}-${item}`}>
                      <ListItemText primary={item} />
                    </ListItem>
                  ))}
                </ul>
              </li>
            ))}
          </List>
        </aside>
        {children}
        <aside className="controls">
          <div className="general">
            speed:
            <br />
            <Slider
              defaultValue={50}
              aria-label="Default"
              valueLabelDisplay="auto"
              className="slide"
              style={{
                padding: "1em 10px",
                width: "9em",
              }}
            />
            <br />
            <Button variant="outlined" sx={{ borderColor: "white", color: "white" }}>Generate New Input</Button>
            <Stack spacing={2} direction="row">
              <IconButton aria-label="pause">
                <PauseIcon sx={{ color: "white" }} />
                <PlayArrowIcon sx={{ color: "white" }} />
              </IconButton>
              <IconButton aria-label="pause">
                <StairsIcon sx={{ color: "white" }} />
              </IconButton>
              <IconButton aria-label="pause">
                <RestartAltIcon sx={{ color: "white" }} />
              </IconButton>
            </Stack>
          </div>
        </aside>
      </body>
    </html>
  );
}
